language: node_js

node_js:
  - 13

os:
  - osx
  - linux

install:
  - |
    npm i
  - |
    if [ $TRAVIS_OS_NAME == "linux" ]; then
      export DISPLAY=':99.0'
      /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
    fi

script:
  - npm run e2e
